### PR TITLE
Allow loading of PostCSS plugins

### LINKED ISSUE #312: Getting a strange PostCSS error after updating Meteor
Hey, thx for your great work.

After updating Meteor to last version + packages..
I'm getting this error running locally which strangely goes away
after I save a file and HR kicks in.. It's more bothersome
because sometimes my deployment breaks because of the same error.
image

My package.json settings:
```
"postcss": {
    "plugins": {
      "autoprefixer": {
        "browsers": [
          "last 2 versions"
        ]
      },
      "postcss-responsive-type": {},
      "lost": {}
    }
  }
```
and I have those libs installed..

Please let me know if you need more information and how to solve this issue.

Thanks again

### PR DESCRIPTION
**Pull request by mitar**
Fixes #312.

### CODE REVIEW

**Comment by mitar** [comment]
See https://github.com/meteor/meteor/issues/9865 for more details.

**Comment by mitar** [comment]
> Have you tried using inputFile.require?

It is not possible to use that because `require` is called from other non-Meteor packages like [postcss-load-config](https://github.com/michael-ciniawsky/postcss-load-config). So sadly this approach is not possible. See discussion here: https://github.com/juliancwirko/meteor-postcss/issues/15

**Comment by nathantreid** [comment]
Ah, so the issue occurs when a Meteor package bundles an npm package and that npm package calls `require` to load a locally installed package?
It's not ideal, but what if you used `akryum:npm-check` to locally install that package? For example, have it automatically locally install `postcss-load-config`, which you can then load with `inputFile.require`?

**Comment by mitar** [comment]
> For example, have it automatically locally install postcss-load-config, which you can then load with inputFile.require?

Yea, you can load `postcss-load-config` with `inputFile.require`, but  `postcss-load-config` calls `require` in turn which then does not find anything you installed in app's `node_modules`.

**Comment by mitar** [comment]
BTW, I think it would be better to discuss workarounds and solutions in https://github.com/meteor/meteor/issues/9865. So whichever standard approach or fix we come up with for this issue we can then use to fix the issue here and in PostCSS and elsewhere. My current best approach I have found is using `app-module-path`. I do not like it, but I could not get anything else to work.

**Comment by Akryum** [comment]
Thanks! :+1:

**Comment by eybarta** [comment]
Hey guys thanks for all your work...! 

I'm trying to use lost grid (PostCSS) plugin inside .vue file,
is there any code example of how to make this work?

I have the following relevant packages:
akryum:vue-component
juliancwirko:postcss

Also using .postcssrc.js file as @mitar suggests, I'm getting no errors
but my styles are not getting compiled through postcss, it just renders as is..

please, any suggestions? haven't been able to find an example anywhere..

thx again.. and hope to see ya in a VueConf soooon! :)

**Comment by mitar** [comment]
You can check how I am doing it here: https://github.com/peer/doc

**Comment by eybarta** [comment]
@mitar thanks for the link.. I cloned it and tried to make the same PostCSS
lib (LostGrid) work with your code and didn't work as well:
screenshot 2018-07-01 11 01 08

All I did was add this to .postcssrc.js file:
```
// In our case, this is done when processing <style> tags inside Vue components.
  else {
    const config = {
      plugins: {
        // To import CSS files from NPM packages.
        'lost': {}
      },
    };
    return config;
  }
```

Am I missing something?

thx again for your time and help on this..

**Pull request merged**
