### PR TITLE
Refactor vue-ssr, switch to maintained fast-render

### PR DESCRIPTION
**Pull request by chris-visser**
This PR fixes a console warning by switching to the maintained cloudspider:fast-render. It also improves some of the code to become more conform the latest code standards

### CODE REVIEW

**Comment by mrauhu** [comment]
@chris-visser, @abecks merged the deprecation warning fix https://github.com/abecks/meteor-fast-render/pull/34 for `staringatlights:fast-render`.

**Comment by chris-visser** [comment]
@mrauhu awesome! Shall I close this one then?

**Comment by mrauhu** [comment]
@chris-visser yes, please.

**Comment by mrauhu** [comment]
@chris-visser I forgot to mention, you need to update the `staringatlights:fast-render` version in the `akryum:vue-ssr` package.

**Comment by chris-visser** [comment]
Thanks for mentioning. Sorry. Have been busy working on some stuff. Thanks for the PR!

**Pull request closed without merging**
