### PR TITLE
[Packages/vue-component] Remove console.log from tag-handler.js. Fixes #382

### LINKED ISSUE #382: Meteor 1.8.2 lots of console logs "module Module {id: "/imports/ui/..."
Since upgrading to Meteor 1.8.2 I'm getting a browser console log message whenever a Vue file is imported:

Screenshot from 2019-12-11 03-37-02

Looks like it's coming from this line: https://github.com/meteor-vue/vue-meteor/blob/6ef113739751c024f02bf67c5c71c6c5da094ae6/packages/vue-component/plugin/tag-handler.js#L182

Where is `module.watch` coming from and how do I set it to true?

Should that `console.log` still be in the code?

### PR DESCRIPTION
**Pull request by wildhart**

### CODE REVIEW

**Comment by mathieustan** [comment]
This PR seems important because we saw logs in production too. @akryum

**Comment by ShaktiDas** [comment]
@Akryum Please merge it ASAP.

**Comment by wildhart** [comment]
@ShaktiDas, if you need this fix urgently you could download my forked [vue-component](https://github.com/wildhart/vue-meteor/tree/bug-%23382/packages/vue-component) package and put it in your `packages` folder.

**Comment by yimankaing** [comment]
i hope you'll merge this soon

**Pull request merged**
