### PR TITLE
[Packages/vue-component] fix: component registration with meteor 1.8.2

### PR DESCRIPTION
**Pull request by jbl2024**
See #364 

require behavior has changed in meteor 1.8.2

### CODE REVIEW

**Comment by jaumeMR** [comment]
This change prevents it from working in legacy browsers. With this small addition I have it working on them:
`js += `\nvar _Vue = require('vue').default;
      if (!_Vue) _Vue = require('vue');
      _Vue.component(__vue_options__.name, __vue_script__);\n``

**Comment by mullojo** [comment]
It would really help me a lot if this fix could be implemented!  @Akryum , have you been able to take a look into this yet?  Much thanks!  I would be happy to contribute on Patreon for all the great work you have done on Meteor + Vue.   I started a project a year ago and have heavily dependant on your packages and work.  Thank you! Bob

**Comment by mullojo** [comment]
Hi @mitar, if @Akryum can't get to this, would you be able to make this change?  I would really appreciate this fix!

**Comment by mitar** [comment]
This looks reasonable for me.

**Pull request merged**
