### PR TITLE
Fix: Update node-sass to make it compatible with Node 14

### PR DESCRIPTION
**Pull request by diavrank**
Fix: https://github.com/meteor-vue/vue-meteor/issues/430

Hi @Akryum , hope you are doing well. Could you help us with this fix?

Thanks.

### CODE REVIEW

**Comment by diavrank** [comment]
@Akryum can you help us with this, please?

**Comment by diavrank** [comment]
Hi @Akryum, sorry for bother you, but I really want this fix, let me know if I can help in other way to make this possible.

**Comment by Akryum** [comment]
Published with `vue-sass` 0.1.3

**Comment by diavrank** [comment]
Thank you very very much for this!

**Pull request merged**
