### PR TITLE
Update vue-coffee to use CoffeeScript 2.0.2

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Bump versions.

### CODE REVIEW

**Comment by Akryum** [comment]
Thanks! 👍

**Comment by GeoffreyBooth** [comment]
@Akryum Do you mind please publishing to Atmosphere?

**Comment by Akryum** [comment]
Sorry, I went to bed. :smile:

**Comment by Akryum** [comment]
It's done :white_check_mark:

**Pull request merged**
