### PR TITLE
Reload Vue template when CSS modules change in the <style> attribute

### PR DESCRIPTION
**Pull request by nathantreid**
When using CSS modules, a change to the class names causes a change to the `$style` computed property and therefore requires the template to be reloaded in order to take effect. 
For example, if I create the following style, reference it in my template, and save my changes, `$style.foo` won't exist on the client after the hot refresh because the client won't know that it needs to reload the entire compiled JS instead of just reloading the render function.

``` html
<style module>
.foo {
 color: red;
}
</style>

<template>
<div :class="$style.foo"></div>
</template>
```

This PR adds cache-checking for the CSS modules output.

### CODE REVIEW

**Comment by Akryum** [comment]
Big thanks for your PR, as usual! Could you please test your changes against the `0.9.0` release before we could merge it?

**Comment by nathantreid** [comment]
Will do. :)

**Comment by nathantreid** [comment]
We've been using this with `0.9.0` no errors, but there's been some weird issues with the styles not always reloading after we make changes, so I'm planning to review this soon in case it's related.

**Comment by Akryum** [comment]
Let me know when this is ready to be merged. :smile:

**Comment by Akryum** [comment]
Any news on this? :smile:

**Pull request merged**
