### PR TITLE
Update babel-compiler for Meteor 1.6.1 compatibility

### LINKED ISSUE #290: Update dependencies to latest version meteor
Hello, the new version of Meteor updates dependencies like babel by making the package incompatible.

### PR DESCRIPTION
**Pull request by nathantreid**
Updates the babel-compiler package as required to support Meteor 1.6.1. Fixes #290.

### CODE REVIEW

**Comment by mwarren2** [comment]
@nathantreid Would you mind doing the same for vue-router2, which has `babel-compiler@6.8.0`?

> Package.registerBuildPlugin({
>   name: 'vue-router',
>   use: [
>     'ecmascript@0.4.4',
>     'caching-compiler@1.0.5',
>     'babel-compiler@6.8.0',
>   ],
>   sources: [
>     'plugin/plugin.js',
>   ],
> })

**Comment by nathantreid** [comment]
Added the update for `vue-router2`. I also have published versions of these packages that contain the fix (`nathantreid:vue-component` and `nathantreid:vue-router2`) that can be used until the `akryum` packages are updated.

**Comment by mwarren2** [comment]
@nathantreid I see that this has been merged. Thanks very much for the work you did on this.

But while I can install your versions, the akryum ones still give the same messages, despite the merge.
Do you have any idea why?

**Comment by Akryum** [comment]
Didn't have time to publish anything (was shopping). 😸

**Comment by mwarren2** [comment]
Ah! Hadn't thought of that. 
Hope you found everything you needed at the shops. Have a good weekend.

**Pull request merged**
